name: health_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  pedometer: ^4.0.2
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  permission_handler: ^10.0.0
  sqflite: ^2.4.1
  path: ^1.9.0
  logging: ^1.3.0
  logger: ^2.5.0
  scoped_model: ^2.0.0
  fl_chart: ^0.70.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  rive: ^0.13.20
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.0
  fluttertoast: ^8.0.9
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/runner.riv